# Default values for sftp-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: docker.pkg.github.com/spring-financial-group/sftp/sftp
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets:
    - github

nameOverride: ""
fullnameOverride: ""

service:
  enabled: true
  type: ClusterIP
  port: 3322

sftpConfig:
  username: sftp
  password: ""
  jailDir: "share"
  encrypted: false
  uid: ""
  gid: ""
  hostKeys: {}
    #secret: name-of-existing-secret
    #keys:
    #- ssh_host_rsa_key
    #- ssh_host_ed25519_key
  authorizedKeys: {}

debug:
  enabled: false
  image:
    repository: quay.io/travelping/nettools
    tag: v1.10.0
    pullPolicy: IfNotPresent

persistentVolume:
  enabled: true
  annotations: {}
  accessModes:
    - ReadWriteOnce
  existingClaim: ""
  size: 20Gi
  # storageClass: "-"
  subPath: ""

resources:
  sftp:
    limits:
      cpu: 300m
      memory: 128Mi
    requests:
      cpu: 300m
      memory: 128Mi
  debug:
    limits:
      cpu: 300m
      memory: 64Mi
    requests:
      cpu: 150m
      memory: 32Mi

nodeSelector: {}

tolerations: []

affinity: {}
